//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperIntendenceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceSet
    {
        public int id { get; set; }
        public int currentValue { get; set; }
        public int group { get; set; }
        public string User_documentNumber { get; set; }
        public string User_documentType { get; set; }
    
        public virtual UserSet UserSet { get; set; }
    }
}
